services:
  url-shortener:
    build: .
    container_name: url_shortener
    ports:
      - "${APP_PORT:-8080}:8080"
    env_file:
      - app/.env
    volumes:
      - url_data:/app
volumes:
  url_data: